# Generated by Django 2.1.5 on 2019-03-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
