# Generated by Django 2.1.5 on 2019-03-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_tagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagging',
            name='document',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagging',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
    ]
